kname: "CodeQL"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '30 1 * * 5'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        # Geconfigureerd voor de Ruby-bestanden in je repository
        language: [ 'ruby' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        # Zorgt voor extra controle op de configuratie
        queries: security-extended,security-and-quality

    # Voor Ruby is geen handmatige build-stap nodig, 
    # dus de 'autobuild' stap is weggelaten om fouten te voorkomen.

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"
        # Forceert de upload van resultaten naar het security tabblad
        upload: true
