name: "Security-Scan"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '30 1 * * 5'

jobs:
  sast:
    name: SAST Scan (CodeQL)
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Deze stap helpt je in de logs te zien of de bestanden er wel zijn
      - name: List files
        run: ls -R

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          # We scannen specifiek Javascript/Typescript voor Juice-Shop
          languages: javascript-typescript
          queries: security-extended

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          # Cruciaal: dit zorgt dat de build 'failed' bij bevindingen
          upload: true
